name: Auto-assign issues to project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: leonsteinhaeuser/project-beta-automations@v2.0.0
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          organization: investigadores-upcruls
          project_id: 2
