name: Auto-assign issues to project

on:
  issues:
    types: [opened]

permissions:
  issues: write
  projects: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Añadir issue al proyecto
        uses: leonsteinhaeuser/project-beta-automations@v2.2.2
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          organization: investigadores-upcruls
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
