name: Auto-assign issues to project

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project and column
        uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/orgs/investigadores-upcruls/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fields: |
            Status=Pendientes
